language: node_js
node_js:
  - "8"
  - "9"
  - "10"
services: mongodb  
cache:  
  directories:
    - "node_modules"
sudo: false
# Added by Michael
before_install:
- cp .env.example config-fb-mbp.env
install:
  - npm install
script:
  - npm run lint
  - npm test